name: Gather Stats

on:
  schedule:
    - cron: '*/5 * * * *' # Runs every 5 minutes
  workflow_dispatch:       # Allows manual execution

permissions:
  contents: write

jobs:
  gather-stats:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        ref: master

    - name: "Run gather_stats.sh"
      shell: bash -euo pipefail {0}
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        ./gather_stats.sh 8 2>&1 | tee gather_stats.log  # Log output to gather_stats.log

    - name: Commit changes
      id: "commit"
      run: |
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git config --global user.name 'github-actions[bot]'
        git add data
        git commit -m 'Update data/' || echo "No changes to commit"
        # FIXME: make this more robust about incoming changes
        # In practice, the other workflow should not modify the data directory, so this *should* be fine.
        git pull --rebase

    - name: Push changes
      uses: ad-m/github-push-action@v0.8.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: master